stages:
  - build

variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_DEPTH: "1"

docker-alpine:
  image: docker:latest
  stage: build
  tags:
    - 'docker-build'
  script:
    - cp /usr/local/bin/docker-init tini
    - rm Dockerfile
    - cp Dockerfile.alpine Dockerfile
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY} 
    - docker build -t ${CI_REGISTRY_IMAGE} . 
    - docker push ${CI_REGISTRY_IMAGE}:alpine
    - docker push ${CI_REGISTRY_IMAGE}:latest

docker-debian:
  image: docker:latest
  stage: build
  tags:
    - 'docker-build'
  script:
    - cp /usr/local/bin/docker-init tini
    - rm Dockerfile
    - cp Dockerfile.debian Dockerfile
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY} 
    - docker build -t ${CI_REGISTRY_IMAGE} . 
    - docker push ${CI_REGISTRY_IMAGE}:debian


